// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jtfmkkaapsvthslsseem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0Zm1ra2FhcHN2dGhzbHNzZWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg3MTcyMzQsImV4cCI6MjA5NDI5MzIzNH0.TKdwmDcfyw4qYaX9_QW4iyzlqDJM9TS8PKiasN2AN-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);